# Generated by Django 4.1.7 on 2023-05-05 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zenflow_userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('to do', 'TO DO'), ('in progress', 'IN PROGRESS'), ('in review', 'IN REVIEW'), ('completed', 'COMPLETED')], default='To Do', max_length=15)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflow_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('date_started', models.DateField()),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='zenflow_userinfo.team')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zenflow_userinfo.employee')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zenflow_workflow.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='workflow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zenflow_workflow.workflow'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2048)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zenflow_workflow.task')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zenflow_userinfo.employee')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zenflow_workflow.task')),
            ],
        ),
    ]
