# Generated by Django 4.1.7 on 2023-05-05 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('email', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=12)),
                ('is_manager', models.BooleanField()),
                ('profile_picture', models.CharField(default='/static/images/default.jpg', max_length=256)),
                ('team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='zenflow_userinfo.team')),
            ],
        ),
    ]
